<?php
$data = array (
  76 => 
  array (
    'cat_id' => '76',
    'cat_name' => 'New arrivals',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 0,
    'id' => '76',
    'name' => 'New arrivals',
  ),
  73 => 
  array (
    'cat_id' => '73',
    'cat_name' => 'Bracelets',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '73',
    'name' => 'Bracelets',
  ),
  75 => 
  array (
    'cat_id' => '75',
    'cat_name' => 'Earring',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '75',
    'name' => 'Earring',
  ),
  90 => 
  array (
    'cat_id' => '90',
    'cat_name' => 'Favorites',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '90',
    'name' => 'Favorites',
  ),
  85 => 
  array (
    'cat_id' => '85',
    'cat_name' => 'Necklace',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '85',
    'name' => 'Necklace',
  ),
  87 => 
  array (
    'cat_id' => '87',
    'cat_name' => 'Ring',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '87',
    'name' => 'Ring',
  ),
  80 => 
  array (
    'cat_id' => '80',
    'cat_name' => 'Inspiration',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '80',
    'name' => 'Inspiration',
  ),
  92 => 
  array (
    'cat_id' => '92',
    'cat_name' => 'Up & running',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '7',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '92',
    'name' => 'Up & running',
  ),
  91 => 
  array (
    'cat_id' => '91',
    'cat_name' => 'Classics',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '91',
    'name' => 'Classics',
  ),
);
?>